adapter_name_or_path: 
bf16: true
cutoff_len: 6000
dataset: train_rl_sharegpt
dataset_dir: data
ddp_timeout: 180000000
deepspeed: cache/ds_z3_config.json
do_train: true
enable_liger_kernel: true
enable_thinking: false
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 4
include_num_input_tokens_seen: true
learning_rate: 5.0e-06
logging_steps: 5
lora_alpha: 32
lora_dropout: 0.05
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: 
num_train_epochs: 1.0
optim: adamw_torch
output_dir: 
packing: false
per_device_train_batch_size: 1
plot_loss: true
pref_beta: 0.1
pref_ftx: 1
pref_loss: sigmoid
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: dpo
template: qwen3
trust_remote_code: true
warmup_steps: 20
