bf16: true
cutoff_len: 12000
dataset: SFT_multirounds_dialog
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: false
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 20
lora_alpha: 32
lora_dropout: 0.05
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: 
num_train_epochs: 2.0
optim: adamw_torch
output_dir: 
packing: false
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: qwen3
trust_remote_code: true
warmup_steps: 30
